workflows: 
 react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini_m2
        cache:
          cache_paths:
          - ~/.gradle/caches
          - ~/Library/Caches/CocoaPods
        integrations:
          app_store_connect: Appstore API Key
        environment:
          groups: 
            - IOS
            - ANDROID
          ios_signing:
            distribution_type: app_store # or: ad_hoc | development | enterprise
            bundle_identifier: com.datn.lapinlearn
          vars:
            XCODE_WORKSPACE: "LapinLearn.xcworkspace" # <-- Put the name of your Xcode workspace here
            XCODE_SCHEME: "LapinLearn" # <-- Put the name of your Xcode scheme here
            APP_ID: $APP_ID # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
          node: v19.7.0
          xcode: latest
          cocoapods: default
        scripts:
          - name: Write env
            script: |
              echo $ENV > ./.env
          - name: Write 'GoogleService-Info.plist'
            script: |
              echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > ./GoogleService-Info.plist
          - name: Write 'google-services.json'
            script: |
              echo $GOOGLE_SERVICES_JSON | base64 --decode > ./google-services.json
          - name: Install npm dependencies
            script: |
              npm install && npx expo prebuild
          - name: Install CocoaPods dependencies
            script: |
              cd ios && pod install
          - name: Set up code signing settings on Xcode project
            script: |
              xcode-project use-profiles --warn-only
          - name: Get the latest build number
            script: | 
              LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number $APP_APPLE_ID)
              cd ./ios # avgtool must run in the folder where xcodeproj file is located
              agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
              echo "Updated build number to $(($LATEST_BUILD_NUMBER + 1))"
          - name: Build ipa for distribution
            script: |
              xcode-project build-ipa \
                --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
                --scheme "$XCODE_SCHEME"
        artifacts:
          - build/ios/ipa/*.ipa
          - /tmp/xcodebuild_logs/*.log
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
          slack:
            channel: '#resources'
            notify_on_build_start: true # To receive a notification when a build starts
            notify:
              success: false # To not receive a notification when a build succeeds
              failure: false # To not receive a notification when a build fails
          email:
            recipients:
              - dophamthanhuy2842003@gmail.com
              - lapinlearnproject@gmail.com
            notify:
              success: true
              failure: false
          