workflows: 
 react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini_m2
        integrations:
          app_store_connect: Appstore API Key
        environment:
          groups: 
            - IOS
          ios_signing:
            distribution_type: app_store # or: ad_hoc | development | enterprise
            bundle_identifier: com.datn.lapinlearn
          vars:
            XCODE_WORKSPACE: "LapinLearn.xcworkspace" # <-- Put the name of your Xcode workspace here
            XCODE_SCHEME: "LapinLearn" # <-- Put the name of your Xcode scheme here
            APP_ID: 6739158736 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
          node: v19.7.0
          xcode: latest
          cocoapods: default
        scripts:
          - name: Write env
            script: |
              echo $ENV > ./.env
          - name: Write 'GoogleService-Info.plist'
            script: |
              echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > ./GoogleService-Info.plist
          - name: Write 'google-services.json'
            script: |
              echo $GOOGLE_SERVICES_JSON | base64 --decode > ./google-services.json
          - name: Install npm dependencies
            script: |
              npm install && npx expo prebuild
          - name: Install CocoaPods dependencies
            script: |
              cd ios && pod install
          - name: Set up code signing settings on Xcode project
            script: |
              xcode-project use-profiles --warn-only
          - name: Increment build number
            script: |
              # Information about getting the latest build version can be found here: https://docs.codemagic.io/knowledge-codemagic/build-versioning/#app-store-or-testflight-latest-build-number
              cd $CM_BUILD_DIR/ios
              LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID")
              agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          - name: Build ipa for distribution
            script: |
              xcode-project build-ipa \
                --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
                --scheme "$XCODE_SCHEME"
        artifacts:
          - build/ios/ipa/*.ipa
          - /tmp/xcodebuild_logs/*.log
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
          email:
            recipients:
              - dophamthanhuy2842003@gmail.com
              - lapinlearnproject@gmail.com
            notify:
              success: true
              failure: false
          app_store_connect:
            auth: integration

            # Configuration related to TestFlight (optional)
            # Note: This action is performed during post-processing.
            submit_to_testflight: true
            # beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
            #   - group name 1
            #   - group name 2

            # Configuration related to App Store (optional)
            # Note: This action is performed during post-processing.
            submit_to_app_store: false