name: Release Artifact IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Access workspace
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies without updating lockfile
        run: npm ci

      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version

      - name: Write env
        run: |
          cat << EOF > .env
            ${{ secrets.ENV }}
          EOF

      - name: Write 'GoogleService-Info.plist'
        run: |
          cat << EOF > ./GoogleService-Info.plist
            ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
          EOF

      - name: Generate 'ios'
        run: npx expo prebuild --platform ios

      - name: Build Cleanup
        run: |
          xcodebuild clean -project ios/LapinLearn.xcodeproj -scheme LapinLearn | xcpretty

      - name: Build Archive
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: ios/LapinLearn.xcodeproj
          workspace-path: ios/LapinLearn.xcworkspace
          scheme: LapinLearn
          configuration: Release
          export-method: app-store
          p12-key-base64: ${{ secrets.IOS_CERT_PASSWORD }}
          p12-cer-base64: ${{ secrets.IOS_CERTIFICATE }}
          mobileprovision-base64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}

      - name: Release ipa artifact
        uses: actions/upload-artifact@v3
        with:
          name: ipa
          path: ios/build/*.ipa

      # Upload IPA file to TestFlight.
      - name: Upload App
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: |
          xcrun altool --upload-app -t ios -f ./**.ipa -u "$APPLEID_USERNAME" -p "$APPLEID_PASSWORD" --verbose
