name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  sonar:
    name: Run SonarQube Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Access workspace
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies without updating lockfile
        run: npm ci

      # Install SonarScanner
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}